
#include "totvs.ch"
#include "topconn.ch"

/*/{Protheus.doc} AFAT006
    Valida se o preço está abaixo da tabela de preço padrão
    @type function
    @version 1.0
    @author Alfred Andersen
    @since 08/08/2023
    @param cProduto, character, Código do produto
    @param nPreco, numeric, preço do produto
    @return logical, Se o produto está abaixo da tabela de preço 
    @requester Kleber Moro
    @consultancy Harpia
    @site www.harpiaconsultoria.com
/*/
User Function AFAT006(cProduto, nPreco)

    Local aArea    as Array
    Local cTabMin  as Character
    Local nDifMin  as Numeric
    Local nPercent as Numeric
    Local lRet     as Logical
    Local cAlias   as Character

    aArea    := GetArea()
    cTabMin  := GETMV("MV_TABMIN")
    nDifMin  := GETMV("MV_DIFMIN")
    nPercent := 0
    lRet     := .F.
    cAlias   := GetNextAlias()

	If Select(cAlias) > 0
		dbSelectArea(cAlias)
		dbCloseArea()
	Endif


    BeginSql Alias cAlias
        SELECT 
            DA1_CODPRO, DA1_CODTAB, SUM(DA1_PRCVEN) PRECO
        FROM 
            %Table:DA1% DA1 (NOLOCK)
        WHERE DA1.%notdel% 
            AND DA1_FILIAL = %xFilial:DA1%
            AND DA1_CODPRO = %Exp:cProduto%
            GROUP BY DA1_CODTAB, DA1_CODPRO
            ORDER BY DA1_CODTAB, DA1_CODPRO
    EndSql

	If (cAlias)->(!Eof())
		
		While (cAlias)->(!Eof())
		
			If (cAlias)->DA1_CODTAB == cTabMin
		
				If nPreco < (cAlias)->PRECO
					nPercent := 100-(nPreco/(cAlias)->PRECO*100)
				Endif
		
				If nPercent > nDifMin

					CONOUT("Este item será bloqueado pela regra... o valor do produto é INFERIOR ao mínimo permitido e a RESERVA NÃO SERA EFETUADA.")

                    lRet := .T.

				Endif

			Endif

			nPercent := 0

			(cAlias)->(dbSkip())		

		Enddo

	Endif

	(cAlias)->(dbCloseArea())

	RestArea(aArea)

Return(lRet)
