#INCLUDE "TOTVS.CH"

/*/{Protheus.doc} AFIN005
    Rotina exclusiva para ajuste do Nosso Numero nos titulos do banco Bradesco
    @type function
    @version 1.0
    @author Alfred Andersen
    @since 3/3/2025
/*/
User Function AFIN005(cBank)

    Local cNossoNum := ""              as Character
    Local cAlias    := GetNextAlias()  as Character
	Local aPars     :={"01", "020201"} as Array

	RpcClearenv()

	RpcSetType( 3 )
	RpcSetEnv( aPars[1], aPars[2] )

    If Alltrim(cBank) == '237'

        BeginSql Alias cAlias
                    
            SELECT 
                R_E_C_N_O_ RECSE1, SE1.*
            FROM 
                %Table:SE1% SE1
            WHERE SE1.%NOTDEL%
                AND E1_FILIAL = '020201'
                AND E1_EMISSAO >= '20241225'
                AND E1_PORTADO = '237'
                AND LEN(E1_NUMBCO) = 11 
            ORDER BY 
                E1_NUM
        EndSql

        If (cAlias)->(!EOF())

            While (cAlias)->(!EOF())

                SE1->(DbGoTo((cAlias)->RECSE1))

                cNossoNum := Alltrim(SE1->E1_NUMBCO) + Alltrim(AFIN005A('02' + SE1->E1_NUMBCO))

                RecLock("SE1",.F.)
                    SE1->E1_NUMBCO  := cNossoNum
                SE1->(MsUnlock())

                (cAlias)->(DbSkip())
            End
        End
    End

    RpcClearEnv()

Return

Static Function AFIN005A(cData)

	Local nL, nD, nP := 0
	nL := Len(cData)
	nD := 0
	nP := 1

	While nL > 0
		nP := nP + 1
		nD := nD + (Val(SubStr(cData, nL, 1)) * nP)

		If nP == 7
			nP := 1
		EndIf

		nL := nL - 1
	End

	nD := 11 - (Mod(nD,11))

	If nD == 10
		cDv := "P"
	ElseIf nD > 10
		cDv := "0"
	Else
		cDv := Str(nD)
	EndIf

Return cDv
