#INCLUDE "TOPCONN.CH"
#INCLUDE "FONT.CH"

/*/{Protheus.doc} RFAT014
	Realiza a impressão do boleto na DANFE - Código herdado do SENTAX_BOLETOS.prw
	@type function
	@version 1.0
	@author Alfred Andersen
	@since 4/1/2024
	@requester Kleber Moro
	@consultancy Harpia
	@site www.harpiaconsultoria.com
/*/
User Function RFAT014(oDanfe, cNota, cSerie, cCliente, cLoja)

	Local aDadosEmp   as Array
	Local aDadosTit   as Array
	Local aDadosBanco as Array
	Local aDatSacado  as Array
	Local aArea       as Array
	Local i           as Numeric
	Local n           as Numeric
	Local CB_RN_NN    as Array
	Local _nVlrAbat   as Numeric
	Local lPrint      as Logical
	Local cNomeBco    as Character
	Local cBordero    as Character
	Local nCont       as Numeric

	Private xDac                as Character
	Private xCarteira           as Character
    Private cAliasSE1           as Character
    Private cSubConta           as Character
	Private nCobRegistrada := 1 as Numeric //AFSOUZA - VARIÁVEL UTILIZADA PARA SUBSTITUIR O ANTIGO MV_PAR10 "COBRANÇA REGISTRADA"


	aDadosEmp   := {}
	aDadosTit   := {}
	aDadosBanco := {}
	aDatSacado  := {}
	i           := 1
    n           := 0
	CB_RN_NN    := {}
	_nVlrAbat   := 0
	lPrint      := .F.
	cNomeBco    := ''
	cBordero    := ""
	cAliasSE1   := GetNextAlias()
	nCont       := 0
	cSubConta   := ""
	xDac        := ''
	xCarteira   := ''
	aArea       := FWGetArea()
	cAliasZZ2   := ""
	cBanco      := ""
	cAgencia    := ""
	cConta      := ""
	cSubConta   := ""

	BeginSql Alias cAliasSE1
                
        SELECT 
            F2_DOC, F2_SERIE, SE1.*, SA1.*, SE1.R_E_C_N_O_ RECSE1
        FROM 
            %Table:SF2% SF2
		INNER JOIN  %Table:SE1% SE1 
			ON E1_FILIAL 	= F2_FILIAL 
			AND E1_CLIENTE 	= F2_CLIENTE 
			AND E1_LOJA 	= F2_LOJA 
			AND E1_NUM 		= F2_DOC 
			AND E1_PREFIXO 	= F2_SERIE 
			AND SE1.%NOTDEL%
        INNER JOIN %Table:SA1% SA1 
            ON A1_COD   = F2_CLIENTE
            AND A1_LOJA = F2_LOJA
            AND SA1.%NOTDEL%
        WHERE SE1.%NOTDEL%
            AND E1_FILIAL   = %xFilial:SE1%
            AND E1_NUM      = %Exp:cNota%
            AND E1_PREFIXO  = %Exp:cSerie%
            //AND E1_XFORMA   = 'BOL'
            AND A1_XIMPBOL  = 'S' 
			AND A1_XBCOBOL  <> '' 
            ORDER BY E1_PARCELA
	EndSql

	Count To nCont

	(cAliasSE1)->(DbGoTop())

	//Se não encontrar registros
	If nCont <= 0

		FWAlertError("O título nº "+cNota+" não atende as regras de impressão de boletos.", '[RFAT014 - 01]')

		Return
	End

	While (cAliasSE1)->(!EOF())

		//Posicionamento na SE1 para uso do legado
		SE1->(DbGoTo((cAliasSE1)->RECSE1))

		aDadosEmp := { SM0->M0_NOMECOM															,; 	//Nome da Empresa
		Transform(SM0->M0_CEPCOB,"@R 99999-999")												,; 	//CEP
		SM0->M0_ENDCOB                                                          				,; 	//Endereço
		AllTrim(SM0->M0_BAIRCOB) +"-"+ AllTrim(SM0->M0_CIDCOB) +"-"+ SM0->M0_ESTCOB				,; 	//Complemento
		"PABX/FAX: "+ SM0->M0_TEL																,; 	//Telefones
		Transform(IIf((cAliasSE1)->A1_XBCOBOL == '033',"08532602000100",SM0->M0_CGC),"@R 99.999.999/9999-99")	,; 	//CGC
		"I.E.: "+ AllTrim(SM0->M0_INSC) 														}	//I.E

		nPorcJur := If(!Empty(SE1->E1_PORCJUR),SE1->E1_PORCJUR, GetMV("ST_PORCJUR") / 30)

		If ((cAliasSE1)->A1_XBCOBOL == '104')

			aBolText := {"Até o vencimento pagável em qualquer banco ou casas lotéricas",;
				"Após o vencimento cobrar juros de 0,2% ao dia",;
				"Não dispensar cobrança de juros em nenhuma hipótese",;
				"Sujeito a protesto após 5 dias do vencimento"}

		ElseIf ((cAliasSE1)->A1_XBCOBOL == '033')

			aBolText := {"Protesto automático após 07 dias (depósito não quita boleto)"	,;
				"Não dispensar cobrança de juros em nenhuma hipotese"			,;
				"Após vencimento cobrar juros ao dia de 0,2% "					,;
				"NOTA FISCAL: " + (cAliasSE1)->E1_NUM									}

		Else

			aBolText := {"Protesto automático após 05 dias (depósito não quita boleto)",;	//Encaminhar ao SERASA após 05 dias corridos do vencimento",;
				"",;
				"Não dispensar cobrança de juros em nenhuma hipótese",; //	"Após vencimento cobrar R$ " + Alltrim(Transform(xMDia, "@E 9,999.99")) + "  por dia de atraso",;
				"Após vencimento cobrar juros ao dia de 0,2% "}

		EndIf

		DbSelectArea("SA6")
		DbSetOrder(1)// filial+ banco + agencia + conta
		If !(DbSeek(xFilial('SA6') + SE1->E1_PORTADO + SE1->E1_AGEDEP + SE1->E1_CONTA))
			ConOut("Banco Não localizado! Verifique os dados digitados e se a Filial esta correta.")
			Return
		EndIF

		DbSelectArea("SEE")
		DbSetOrder(1)// filial+ banco + agencia + conta + subconta
		If !(DbSeek(xFilial('SEE')+SA6->(A6_COD+A6_AGENCIA+A6_NUMCON)+cSubConta,.T.))
			ConOut("Parametro de banco nao localizado! Verifique os dados digitados e se a Filial esta correta.")
			Return
		EndIf

		//Chama função para gerar bordero
		/*
		If Empty((cAliasSE1)->E1_NUMBOR)
			cBordero :=	U_AFIN002(SA6->A6_COD,SA6->A6_AGENCIA,SA6->A6_NUMCON)
		Else
			cBordero := (cAliasSE1)->E1_NUMBOR
		EndIf
		*/

		xDac  := ALLTRIM(SA6->A6_DVCTA)

		If (cAliasSE1)->A1_XBCOBOL == '341'
			xCarteira	:= '109'
			cNomeBco 	:= 'ITAU'
		ElseIf (cAliasSE1)->A1_XBCOBOL == '104'
			xCarteira	:= 'RG'
			cNomeBco 	:= ''
		ElseIf (cAliasSE1)->A1_XBCOBOL == '237'
			xCarteira	:= '02'
			cNomeBco 	:= 'BRADESCO'
		ElseIf (cAliasSE1)->A1_XBCOBOL == '001'
			xCarteira	:= '17'
			cNomeBco 	:= 'BANCO DO BRASIL'
		ElseIf (cAliasSE1)->A1_XBCOBOL == '399'
			xCarteira	:= 'CNR'
			cNomeBco 	:= 'HSBC'
		ElseIf (cAliasSE1)->A1_XBCOBOL == '033'
			xCarteira	:= '101'
			cNomeBco 	:= 'SANTANDER'
		Else
			xCarteira	:= '00'
			cNomeBco 	:= Alltrim(SA6->A6_NOME)
		End

		aDadosBanco := { SA6->A6_COD				,;   //1 Numero do Banco
                        AllTrim(cNomeBco)			,;   //2 Nome do Banco
                        AllTrim(SA6->A6_AGENCIA)	,;   //3 Agência
                        AllTrim(SA6->A6_NUMCON)		,;   //4 Conta Corrente
                        xCarteira					,;   //5 Carteira
                        SA6->A6_COD					,;   //6 Codigo no SA6
                        AllTrim(SEE->EE_CODEMP)     }    //7 Codigo de Convenio

		dbSelectArea('SA1')
		SA1->(DBSeek(xFilial('SA1') + (cAliasSE1)->E1_CLIENTE + (cAliasSE1)->E1_LOJA))

		aDatSacado := { AllTrim(SA1->A1_NOME)	,;   //Razão Social
                        AllTrim(SA1->A1_COD )	,;   //Código
                        AllTrim(SA1->A1_END )	,;   //Endereço
                        AllTrim(SA1->A1_MUN )	,;   //Cidade
                        SA1->A1_EST				,;   //Estado
                        SA1->A1_CEP				,;   //CEP
                        SA1->A1_CGC				,;   //CGC
                        SA1->A1_XMSGBOL         } 			 //Mensagem fixa no boleto

		_nVlrAbat := SomaAbat((cAliasSE1)->E1_PREFIXO,(cAliasSE1)->E1_NUM,(cAliasSE1)->E1_PARCELA,"R",1,,(cAliasSE1)->E1_CLIENTE,(cAliasSE1)->E1_LOJA)
		_cPrefixo := (cAliasSE1)->E1_PREFIXO
		_nTitulo  := (cAliasSE1)->E1_NUM

		IF !Empty((cAliasSE1)->E1_PARCELA)
			_nTitulo  := _nTitulo + ' - ' + (cAliasSE1)->E1_PARCELA
		ENDIF

		_dEmissao := STOD((cAliasSE1)->E1_EMISSAO)
		_dVenc    := STOD((cAliasSE1)->E1_VENCREA)
		_nSaldo   := (cAliasSE1)->E1_SALDO
		_nDecres  := (cAliasSE1)->E1_DECRESC
		_nAcres   := (cAliasSE1)->E1_ACRESC
		xParcela  := (cAliasSE1)->E1_PARCELA

		CB_RN_NN := Ret_cBarra( SubStr(aDadosBanco[1],1,3)+'9', aDadosBanco[3],AllTrim(aDadosBanco[4]) + AllTrim(xDac) ,;
			                    aDadosBanco[5],AllTrim((cAliasSE1)->E1_NUM)+AllTrim((cAliasSE1)->E1_PARCELA),(((cAliasSE1)->E1_SALDO+_nAcres)-_nDecres),;
                                aDadosBanco[6],STOD((cAliasSE1)->E1_VENCREA),(cAliasSE1)->E1_PREFIXO)

		aDadosTit := { AllTrim(_nTitulo)   					,; //Número do título
                        _dEmissao            				,; //Data da emissão do título
                        Date()               				,; //Data da emissão do boleto
                        _dVenc              		   		,; //Data do vencimento
                        ((_nSaldo + _nAcres) - _nDecres)	,; //Valor do título
                        CB_RN_NN[3]							,; //Nosso Numero
                        xParcela                            }  //parcela incluido em 18/02/03
                        //(_nSaldo - _nVlrAbat),;		       //Valor do título

		Impress(oDanfe,aDadosEmp,aDadosTit,aDadosBanco,aDatSacado,aBolText,CB_RN_NN)
		n := n + 1
		i := i + 1

		//oDanfe:EndPage()

		(cAliasSE1)->(dbSkip())

	EndDo

	FWRestArea( aArea )

Return nil

/*/{Protheus.doc} Impress
	Impressão do boleto - Código herdado do SENTAX_BOLETOS.prw
	@type function
	@version 1.0
	@author Alfred Andersen
	@since 4/1/2024
/*/
Static Function Impress(oDanfe,aDadosEmp,aDadosTit,aDadosBanco,aDatSacado,aBolText,CB_RN_NN)  //Impress(oDanfe,aBitmap,aDadosEmp,aDadosTit,aDadosBanco,aDatSacado,aBolText,CB_RN_NN)

	Local nI        as Numeric
	Local cLogo     as Character
	Local _cNN      as Character
	Local cMsg1     as Character
	Local cMsg2     as Character
	Local cMsg3     as Character
	Local cDVAge    as Character
	Local cCodBen33 as Character
	Local oFon8n    as Object
	Local oFon8     as Object
	Local oFon18    as Object
	Local oFon15n   as Object

	nI        := 0
	cLogo     := ''
	_cNN      := ''
	cMsg1     := ''
	cMsg2     := ''
	cMsg3     := ''
	cDVAge    := AllTrim(POSICIONE("SA6",1,XFILIAL("SA6")+(cAliasSE1)->A1_XBCOBOL+aDadosBanco[3],"A6_DVAGE"))
	cCodBen33 := '0173839'
	oFon8n    := TFontEx():New(oDanfe, "Arial", 07, 07, .T., .T., .F.)
	oFon8     := TFontEx():New(oDanfe, "Arial", 08, 08, .F., .T., .F.)
	oFon18    := TFontEx():New(oDanfe, "Arial", 18, 18, .T., .T., .F.)
	oFon15n   := TFontEx():New(oDanfe, "Arial", 13, 13, .T., .T., .F.)

	If ( (cAliasSE1)->A1_XBCOBOL == '341' )
		cLogo := "\system\logoitau.bmp"
		_cNN := '109/'+aDadosTit[6]
	ElseIf ( (cAliasSE1)->A1_XBCOBOL == '104' )
		cLogo :='\system\caixa.bmp'
		_cNN := aDadosTit[6]
	ElseIf (cAliasSE1)->A1_XBCOBOL == "237"
		cLogo := "\system\logobradesco.bmp"
		_cNN := AllTrim(aDadosTit[6])
	ElseIf ( (cAliasSE1)->A1_XBCOBOL == '399' )
		cLogo :='\system\hsbc.bmp'
		_cNN := aDadosTit[6]
	ElseIf ( (cAliasSE1)->A1_XBCOBOL == '001' )
		cLogo :='\system\BB.bmp'
		_cNN := aDadosTit[6]
	ElseIf ( (cAliasSE1)->A1_XBCOBOL == '033' )

		cDVAge   := AllTrim(POSICIONE("SA6",1,XFILIAL("SA6") + (cAliasSE1)->A1_XBCOBOL + PADR(aDadosBanco[3],5,"") + aDadosBanco[4],"A6_DVAGE"))

		cLogo :='\system\SANTANDER.bmp'

		_cNN := aDadosTit[6]

		_cE1Numbco	:=	Alltrim(_cNN) + Alltrim(u_digMod11(_cNN))

	EndIf

	If ((cAliasSE1)->A1_XBCOBOL == '341')
		cMsg1 := "ATÉ O VENCIMENTO, PREFERENCIALMENTE NO ITAÚ"
		cMsg2 := "APÓS O VENCIMENTO, SOMENTE NO ITAÚ"
		cMSg3 := ''
	ElseIf ((cAliasSE1)->A1_XBCOBOL == '104')
		cMsg1 := "PREFERENCIALMENTE NAS LOTÉRICAS ATÉ O VALOR LIMITE"
		cMsg2 := ''
		cMSg3 := ''
	ElseIf (cAliasSE1)->A1_XBCOBOL == "237"
		cMsg1 := "PAGAVEL PREFERENCIALMENTE NA REDE BRADESCO OU NO "
		cMsg2 := "BRADESCO EXPRESSO"
		cMSg3 := ""
	ElseIf ((cAliasSE1)->A1_XBCOBOL == '399')
		cMsg1 := "PAGAR PREFERENCIALMENTE EM AGÊNCIA DO HSBC"
		cMsg2 := ''
		cMSg3 := ''
	ElseIf ((cAliasSE1)->A1_XBCOBOL == '001')
		//cMsg1 := "Pagável em qualquer banco até o vencimento. Após, atualize o boleto no site bb.com.br"
		cMsg1 := "Pagável em qualquer banco."
		cMsg2 := ''
		cMSg3 := ''
	ElseIf ((cAliasSE1)->A1_XBCOBOL == '033')
		//cMsg1 := "Pagável em qualquer banco até o vencimento. Após, atualize o boleto no site bb.com.br"
		cMsg1 := "PAGÁVEL PREFERENCIALMENTE NO BANCO SANTANDER"
		cMsg2 := ''
		cMSg3 := ''
	EndIf

	oDanfe:StartPage() // Inicia uma nova página

    /*----------------------------------------------/
    /	Primeira Via								/
    /----------------------------------------------*/

	nRow1 := 010 //006,002

	//Linhas verticais ao lado do código do banco
	oDanfe:Line (nRow1+000,113,nRow1+014, 113)
	oDanfe:Line (nRow1+000,175,nRow1+014, 175)

	If ((cAliasSE1)->A1_XBCOBOL == '104')
		oDanfe:SayBitmap(-005,000,cLogo,100,30)
		oDanfe:Say  (nRow1+014,115,aDadosBanco[1]+"-0",oFon18:oFont)

	ElseIf ((cAliasSE1)->A1_XBCOBOL == '399')
		oDanfe:SayBitmap(-005,000,cLogo,100,30)
		oDanfe:Say  (nRow1+014,115,aDadosBanco[1]+"-9",oFon18:oFont)

	ElseIf (cAliasSE1)->A1_XBCOBOL == "237"
		oDanfe:SayBitmap(-004,000,cLogo,110,25)
		oDanfe:Say  (nRow1+014,115,aDadosBanco[1]+"-2",oFon18:oFont)

	ElseIf ((cAliasSE1)->A1_XBCOBOL == '033')
		oDanfe:SayBitmap(-005,000,cLogo,90,25)	
		oDanfe:Say  (nRow1+014,115,aDadosBanco[1]+"-7",oFon18:oFont)

	ElseIf ((cAliasSE1)->A1_XBCOBOL == '341')
		oDanfe:SayBitmap(000,000,cLogo,100,25)
		oDanfe:Say  (nRow1+013,119,aDadosBanco[1]+"-7",oFon18:oFont)

	Else
		oDanfe:SayBitmap(000,000,cLogo,100,25)
		oDanfe:Say  (nRow1+013,119,aDadosBanco[1]+"-9",oFon18:oFont)

	EndIf

	oDanfe:Say  (nRow1+013,490,"Comprovante de Entrega",oFon8:oFont)

	oDanfe:Say  (nRow1+027,002,"Cedente",oFon8n:oFont)
	oDanfe:Say  (nRow1+038,002 ,aDadosEmp[1],oFon8:oFont)				//Nome + CNPJ

	oDanfe:Say  (nRow1+027,270,"Agência/Código do Cedente",oFon8n:oFont)
	If (cAliasSE1)->A1_XBCOBOL == '104'
		oDanfe:Say  (nRow1+038,280,ALLTRIM(aDadosBanco[3])+'/'+ALLTRIM(aDadosBanco[7]),oFon8:oFont)
	ElseIf (cAliasSE1)->A1_XBCOBOL == '033'
		oDanfe:Say  (nRow1+038,280,ALLTRIM(aDadosBanco[3])+'/'+cCodBen33,oFon8:oFont)
	Else
		oDanfe:Say  (nRow1+038,280,ALLTRIM(aDadosBanco[3]+"-"+cDVAge)+' / '+ALLTRIM(aDadosBanco[4])+IIF(xDac <> '','-' + xDac,'') ,oFon8:oFont)
	Endif

	oDanfe:Say  (nRow1+027,385,"Nro. Documento",oFon8n:oFont)
	oDanfe:Say  (nRow1+038,410, aDadosTit[1],oFon8:oFont) //Prefixo +Numero+Parcela

	oDanfe:Say  (nRow1+052,002 ,"Sacado",oFon8n:oFont)
	oDanfe:Say  (nRow1+065,002 ,SUBSTRING(aDatSacado[1],1,50),oFon8:oFont)				//Nome

	oDanfe:Say  (nRow1+052,270,"Vencimento",oFon8n:oFont)
	oDanfe:Say  (nRow1+065,280,dtoc(aDadosTit[4]),oFon8:oFont)

	oDanfe:Say  (nRow1+052,385,"Valor do Documento",oFon8n:oFont)
	oDanfe:Say  (nRow1+065,410,AllTrim(Transform(aDadosTit[5],"@E 999,999,999.99")),oFon8:oFont)

	oDanfe:Say  (nRow1+095,002,"Recebi(emos) o bloqueto/título",oFon8:oFont)
	oDanfe:Say  (nRow1+110,002,"com as características acima.",oFon8:oFont)
	oDanfe:Say  (nRow1+075,270,"Data",oFon8n:oFont)
	oDanfe:Say  (nRow1+075,370,"Assinatura",oFon8n:oFont)
	oDanfe:Say  (nRow1+098,270,"Data",oFon8n:oFont)
	oDanfe:Say  (nRow1+098,370,"Entregador",oFon8n:oFont)

	//Linhas horizontais
	oDanfe:Line (nRow1+015, 002,nRow1+015,620 )
	oDanfe:Line (nRow1+045, 002,nRow1+045,498 )
	oDanfe:Line (nRow1+068, 002,nRow1+068,498 )
	oDanfe:Line (nRow1+090, 268,nRow1+090,498 )
	oDanfe:Line (nRow1+115, 002,nRow1+115,620 )

	//Linhas verticais
	oDanfe:Line (nRow1+015,268,nRow1+115,268 )
	oDanfe:Line (nRow1+068,368,nRow1+115,368 )
	oDanfe:Line (nRow1+015,383,nRow1+067,383 )
	oDanfe:Line (nRow1+015,498,nRow1+115,498 )

	oDanfe:Say  (nRow1+030,500,"(  )Mudou-se"                 ,oFon8n:oFont)
	oDanfe:Say  (nRow1+040,500,"(  )Ausente"                  ,oFon8n:oFont)
	oDanfe:Say  (nRow1+050,500,"(  )Não existe nº indicado"   ,oFon8n:oFont)
	oDanfe:Say  (nRow1+060,500,"(  )Recusado"                 ,oFon8n:oFont)
	oDanfe:Say  (nRow1+070,500,"(  )Não procurado"            ,oFon8n:oFont)
	oDanfe:Say  (nRow1+080,500,"(  )Endereço insuficiente"    ,oFon8n:oFont)
	oDanfe:Say  (nRow1+090,500,"(  )Desconhecido"             ,oFon8n:oFont)
	oDanfe:Say  (nRow1+100,500,"(  )Falecido"                 ,oFon8n:oFont)
	oDanfe:Say  (nRow1+110,500,"(  )Outros(anotar no verso)"  ,oFon8n:oFont)


	/*****************/
	/* SEGUNDA PARTE */
	/*****************/

	nRow2 := 0

	//Pontilhado separador
	For nI := 002 to 610 Step 20
		oDanfe:Line(nRow2+130, nI,nRow2+130, nI+10)
	Next nI

	//Linhas verticais ao lado do código do banco
	oDanfe:Line (nRow2+156,113,nRow2+172,113)
	oDanfe:Line (nRow2+156,175,nRow2+172,175)

	If ((cAliasSE1)->A1_XBCOBOL == '104')
		oDanfe:SayBitmap(145,000,cLogo,100,25)
		oDanfe:Say  (nRow2+165,119,aDadosBanco[1]+"-0",oFon18:oFont)

	ElseIf ((cAliasSE1)->A1_XBCOBOL == '399')
		oDanfe:SayBitmap(145,000,cLogo,100,25)
		oDanfe:Say  (nRow2+165,119,aDadosBanco[1]+"-9",oFon18:oFont)

	ElseIf (cAliasSE1)->A1_XBCOBOL == "237"
		oDanfe:SayBitmap(143,000,cLogo,110,25)
		oDanfe:Say  (nRow2+165,119,aDadosBanco[1]+"-2",oFon18:oFont)

	ElseIf ((cAliasSE1)->A1_XBCOBOL == '033')
		oDanfe:SayBitmap(145,000,cLogo,90,25)
		oDanfe:Say  (nRow2+165,119,aDadosBanco[1]+"-7",oFon18:oFont)

	ElseIf ((cAliasSE1)->A1_XBCOBOL == '341')
		oDanfe:SayBitmap(145,000,cLogo,100,25)
		oDanfe:Say  (nRow2+165,119,aDadosBanco[1]+"-7",oFon18:oFont)

	Else
		oDanfe:SayBitmap(145,000,cLogo,100,25)
		oDanfe:Say  (nRow2+165,119,aDadosBanco[1]+"-9",oFon18:oFont)

	EndIf

	oDanfe:Say  (nRow2+165,455,"Recibo do Sacado",oFon8:oFont)

	//Linhas Horizontais
	oDanfe:Line (nRow2+172,002,nRow2+172,620 )//local de pagto
	oDanfe:Line (nRow2+203,002,nRow2+203,620 )//cedente
	oDanfe:Line (nRow2+228,002,nRow2+228,620 )//data de emissao
	oDanfe:Line (nRow2+248,002,nRow2+248,620 )//uso do banco
	oDanfe:Line (nRow2+268,002,nRow2+268,620 )//instruções
	
	oDanfe:Line (nRow2+288,455,nRow2+288,620 )//outras deduções
	oDanfe:Line (nRow2+308,455,nRow2+308,620 )//mora multa
	oDanfe:Line (nRow2+328,455,nRow2+328,620 )//outros acrescimos
	oDanfe:Line (nRow2+348,455,nRow2+348,620 )//valor cobrado

	oDanfe:Line (nRow2+368,002,nRow2+368,620 )//sacado
	oDanfe:Line (nRow2+438,002,nRow2+438,620 )//sacador/avalista

	//Linhas Verticais
	oDanfe:Line (nRow2+172,455,nRow2+368,455)
	oDanfe:Line (nRow2+228,113,nRow2+248,113)//nº documento
	oDanfe:Line (nRow2+228,248,nRow2+248,248)//especie doc
	oDanfe:Line (nRow2+228,340,nRow2+248,340)//aceite
	oDanfe:Line (nRow2+228,373,nRow2+248,373)//data processamento

	oDanfe:Line (nRow2+248,063,nRow2+268,063)//cip
	oDanfe:Line (nRow2+248,113,nRow2+268,113)//carteira
	oDanfe:Line (nRow2+248,178,nRow2+268,178)//moeda
	oDanfe:Line (nRow2+248,248,nRow2+268,248)//quantidade
	oDanfe:Line (nRow2+248,373,nRow2+268,373)//valor

	oDanfe:Say  (nRow2+185,002 ,"Local de Pagamento",oFon8n:oFont)
	oDanfe:Say  (nRow2+195,002 ,cMsg1 + cMsg2 + cMsg3 ,oFon8:oFont)

	oDanfe:Say  (nRow2+185,460,"Vencimento",oFon8n:oFont)
	oDanfe:Say  (nRow2+200,545, dtoc(aDadosTit[4]), oFon8:oFont)

	oDanfe:Say  (nRow2+210,002 ,"Cedente"                                       ,oFon8n:oFont)
	oDanfe:Say  (nRow2+215,050 ,Alltrim(aDadosEmp[1])+" - CNPJ: "+aDadosEmp[6]	,oFon8:oFont) //Nome + CNPJ
	oDanfe:Say  (nRow2+225,050 ,AllTrim(aDadosEmp[3]) +" - "+ aDadosEmp[4] +" CEP: " + aDadosEmp[2],oFon8:oFont)

	oDanfe:Say  (nRow2+0210,460,"Agência/Código Cedente",oFon8n:oFont)
	If (cAliasSE1)->A1_XBCOBOL == '104'
		oDanfe:Say  (nRow2+225,505,ALLTRIM(aDadosBanco[3])+'/'+ALLTRIM(aDadosBanco[7]),oFon8:oFont)

	ElseIf (cAliasSE1)->A1_XBCOBOL == '033'
		oDanfe:Say  (nRow2+225,505,ALLTRIM(aDadosBanco[3])+'/'+cCodBen33,oFon8:oFont)

	Else
		oDanfe:Say  (nRow2+225,505,ALLTRIM(aDadosBanco[3]+"-"+cDVAge)+' / '+ALLTRIM(aDadosBanco[4])+IIF(xDac <> '','-' + xDac,'') ,oFon8:oFont)

	Endif

	oDanfe:Say  (nRow2+235,002 ,"Data de Emissão" 	,oFon8n:oFont)
	oDanfe:Say  (nRow2+245,002, dtoc(aDadosTit[2])	,oFon8:oFont)

	oDanfe:Say  (nRow2+235,115 ,"Nro. Documento"    ,oFon8n:oFont)
	oDanfe:Say  (nRow2+245,145 ,aDadosTit[1]		,oFon8:oFont)

	oDanfe:Say  (nRow2+235,250,"Espécie Doc."		,oFon8n:oFont)
	oDanfe:Say  (nRow2+245,265,"DM"   				,oFon8:oFont) 

	oDanfe:Say  (nRow2+235,343,"Aceite"             ,oFon8n:oFont)
	oDanfe:Say  (nRow2+245,353,"N"                  ,oFon8:oFont)

	oDanfe:Say  (nRow2+235,375,"Data Processamento" ,oFon8n:oFont)
	oDanfe:Say  (nRow2+245,395,dtoc(aDadosTit[3])	,oFon8:oFont) 

	oDanfe:Say  (nRow2+235,460,"Carteira/Nosso Número"  ,oFon8n:oFont)
	IF ((cAliasSE1)->A1_XBCOBOL=='104')
		oDanfe:Say  (nRow2+245, 505,LEFT(_cNN,2)+'/'+SUBS(_cNN,3,LEN(_cNN)-3)+'-'+RIGHT(_cNN,1),oFon8:oFont)

	ElseIF((cAliasSE1)->A1_XBCOBOL=='399' .AND. nCobRegistrada == 1 )
		oDanfe:Say  (nRow2+245, 505,SUBS(_cNN,1,LEN(_cNN)-1)+'-'+RIGHT(_cNN,1)					,oFon8:oFont)

	ElseIF((cAliasSE1)->A1_XBCOBOL=='399' .AND. nCobRegistrada <> 1 )
		oDanfe:Say  (nRow2+245, 505,SUBS(_cNN,1,LEN(_cNN)-3)+'-'+RIGHT(_cNN,3)					,oFon8:oFont)

	ElseIf (cAliasSE1)->A1_XBCOBOL == "237"
		oDanfe:Say  (nRow2+245, 505,xCarteira +"/"+ SubStr(_cNN,1,11) +"-"+ Right(_cNN,1)		,oFon8:oFont)    

	ElseIf (cAliasSE1)->A1_XBCOBOL == "033"
		oDanfe:Say  (nRow2+245, 505,_cE1Numbco		,oFon8:oFont) 	            

	Else
		oDanfe:Say  (nRow2+245, 505,"3097391"+_cNN	,oFon8:oFont)

	EndIf

	oDanfe:Say  (nRow2+255,002 ,"Uso do Banco"               ,oFon8n:oFont)
	//oDanfe:Say  (nRow2+265,002 ,"8650"		                 ,oFon8:oFont)

	oDanfe:Say  (nRow2+255,065 ,"CIP"		                 ,oFon8n:oFont)
	oDanfe:Say  (nRow2+265,070 ,"000"		                 ,oFon8:oFont)

	oDanfe:Say  (nRow2+255,115 ,"Carteira"                   ,oFon8n:oFont)
	oDanfe:Say  (nRow2+265,135 ,xCarteira                    ,oFon8:oFont)

	oDanfe:Say  (nRow2+255,180 ,"Moeda"                      ,oFon8n:oFont)
	oDanfe:Say  (nRow2+265,200 ,"R$"                         ,oFon8:oFont)

	oDanfe:Say  (nRow2+255,250,"Quantidade"                  ,oFon8n:oFont)
	oDanfe:Say  (nRow2+255,375,"Valor"                       ,oFon8n:oFont)

	oDanfe:Say  (nRow2+255,460,"Valor do Documento"          ,oFon8n:oFont)
	oDanfe:Say  (nRow2+265, 545, AllTrim(Transform(aDadosTit[5],"@E 999,999,999.99")) , oFon8:oFont)

	oDanfe:Say  (nRow2+275,002 ,"Instruções (Todas informações deste bloqueto são de exclusiva responsabilidade do cedente)",oFon8n:oFont)
	oDanfe:Say  (nRow2+295,002 ,aBolText[1] ,oFon8:oFont)
	oDanfe:Say  (nRow2+305,002 ,aBolText[2] ,oFon8:oFont)
	oDanfe:Say  (nRow2+315,002 ,aBolText[3] ,oFon8:oFont)
	oDanfe:Say  (nRow2+325,002 ,aBolText[4] ,oFon8:oFont)

	oDanfe:Say  (nRow2+275,460,"(-)Desconto/Abatimento"                         ,oFon8n:oFont)
	oDanfe:Say  (nRow2+295,460,"(-)Outras Deduções"                             ,oFon8n:oFont)
	oDanfe:Say  (nRow2+315,460,"(+)Mora/Multa"                                  ,oFon8n:oFont)
	oDanfe:Say  (nRow2+335,460,"(+)Outros Acréscimos"                           ,oFon8n:oFont)
	oDanfe:Say  (nRow2+355,460,"(=)Valor Cobrado"                               ,oFon8n:oFont)

	oDanfe:Say  (nRow2+365,002 ,"Sacado"                                         ,oFon8n:oFont)
	oDanfe:Say  (nRow2+385,100 ,aDatSacado[1]+" ("+aDatSacado[2]+")"             ,oFon8:oFont)
	oDanfe:Say  (nRow2+400,100 ,aDatSacado[3]                                    ,oFon8:oFont)
	oDanfe:Say  (nRow2+415,100 ,aDatSacado[6]+"    "+aDatSacado[4]+" - "+aDatSacado[5],oFon8:oFont) // CEP+Cidade+Estado

	if Len(AllTrim(aDatSacado[7])) == 14
		oDanfe:Say  (nRow2+430,100 ,"CNPJ: "+TRANSFORM(aDatSacado[7],"@R 99.999.999/9999-99"),oFon8:oFont) // CGC
	Else
		oDanfe:Say  (nRow2+430,100 ,"CPF: "+TRANSFORM(aDatSacado[7],"@R 999.999.999-99"),oFon8:oFont) 	// CPF
	EndIf

	oDanfe:Say  (nRow2+430,400,Substr(aDadosTit[6],1,3)+Substr(aDadosTit[6],4)  ,oFon8:oFont)

	oDanfe:Say  (nRow2+435,002 ,"Sacador/Avalista",oFon8n:oFont)
	oDanfe:Say  (nRow2+445,370,"Autenticação Mecânica",oFon8n:oFont)


	/******************/
	/* TERCEIRA PARTE */
	/******************/

	//nRow3 := 395
	nRow3 := 355

	For nI := 002 To 610 Step 20
		oDanfe:Line(nRow3+140, nI, nRow3+140, nI+10)
	Next nI

	//Linhas verticais ao lado do código do banco
	oDanfe:Line (nRow3+156,113,nRow3+172,113)
	oDanfe:Line (nRow3+156,175,nRow3+172,175)

	If ((cAliasSE1)->A1_XBCOBOL == '104')
		oDanfe:SayBitmap(nRow3+150,000,cLogo,100,25)
		oDanfe:Say  (nRow3+170,119,aDadosBanco[1]+"-0",oFon18:oFont)
		oDanfe:Say  (nRow3+170,180,CB_RN_NN[2],oFon15n:oFont)	

	ElseIf ((cAliasSE1)->A1_XBCOBOL == '399')
		oDanfe:SayBitmap(nRow3+150,000,cLogo,100,25)
		oDanfe:Say  (nnRow3+170,119,aDadosBanco[1]+"-9",oFon18:oFont)
		oDanfe:Say  (nRow3+170,180,CB_RN_NN[2],oFon15n:oFont)	

	ElseIf (cAliasSE1)->A1_XBCOBOL == "237"
		oDanfe:SayBitmap(nRow3+143,000,cLogo,110,25)
		oDanfe:Say  (nRow3+170,119,aDadosBanco[1]+"-2",oFon18:oFont)
		oDanfe:Say  (nRow3+170,180,CB_RN_NN[2],oFon15n:oFont)	

	ElseIf ((cAliasSE1)->A1_XBCOBOL == '033')
		oDanfe:SayBitmap(nRow3+145,000,cLogo,90,25)
		oDanfe:Say  (nRow3+170,119,aDadosBanco[1]+"-7",oFon18:oFont)
		oDanfe:Say  (nRow3+170,180,CB_RN_NN[2],oFon15n:oFont)	

	ElseIf ((cAliasSE1)->A1_XBCOBOL == '341')
		oDanfe:SayBitmap(nRow3+145,000,cLogo,100,25)
		oDanfe:Say  (nRow3+170,119,aDadosBanco[1]+"-7",oFon18:oFont)
		oDanfe:Say  (nRow3+170,180,CB_RN_NN[2],oFon15n:oFont)	
	Else
		oDanfe:SayBitmap(nRow3+150,000,cLogo,100,25)
		oDanfe:Say  (nRow3+170,119,aDadosBanco[1]+"-9",oFon18:oFont)
		oDanfe:Say  (nRow3+170,180,CB_RN_NN[2],oFon15n:oFont)	
	EndIf

	//Linhas Horizontais
	oDanfe:Line (nRow3+172,002,nRow3+172,620 )//local de pagto
	oDanfe:Line (nRow3+203,002,nRow3+203,620 )//cedente
	oDanfe:Line (nRow3+228,002,nRow3+228,620 )//data de emissao
	oDanfe:Line (nRow3+248,002,nRow3+248,620 )//uso do banco
	oDanfe:Line (nRow3+268,002,nRow3+268,620 )//instruções
								
	oDanfe:Line (nRow3+288,455,nRow3+288,620 )//outras deduções
	oDanfe:Line (nRow3+308,455,nRow3+308,620 )//mora multa
	oDanfe:Line (nRow3+328,455,nRow3+328,620 )//outros acrescimos
	oDanfe:Line (nRow3+348,455,nRow3+348,620 )//valor cobrado

	oDanfe:Line (nRow3+368,002,nRow3+368,620 )//sacado
	oDanfe:Line (nRow3+412,002,nRow3+412,620 )//sacador/avalista

	//Linhas Verticais
	oDanfe:Line (nRow3+172,455,nRow3+368,455)
	oDanfe:Line (nRow3+228,113,nRow3+248,113)//nº documento
	oDanfe:Line (nRow3+228,248,nRow3+248,248)//especie doc
	oDanfe:Line (nRow3+228,340,nRow3+248,340)//aceite
	oDanfe:Line (nRow3+228,373,nRow3+248,373)//data processamento

	oDanfe:Line (nRow3+248,063,nRow3+268,063)//cip
	oDanfe:Line (nRow3+248,113,nRow3+268,113)//carteira
	oDanfe:Line (nRow3+248,178,nRow3+268,178)//moeda
	oDanfe:Line (nRow3+248,248,nRow3+268,248)//quantidade
	oDanfe:Line (nRow3+248,373,nRow3+268,373)//valor


	oDanfe:Say  (nRow3+185,002 ,"Local de Pagamento"		,oFon8n:oFont)
	oDanfe:Say  (nRow3+195,002 ,cMsg1 + cMsg2 + cMsg3 		,oFon8:oFont)

	oDanfe:Say  (nRow3+185,460,"Vencimento"					,oFon8n:oFont)
	oDanfe:Say  (nRow3+200, 545, dtoc(aDadosTit[4])			,oFon8:oFont)

	oDanfe:Say  (nRow3+210,002 ,"Cedente",oFon8n:oFont)
	oDanfe:Say  (nRow3+215,050 ,Alltrim(aDadosEmp[1])+" - CNPJ: "+aDadosEmp[6]				,oFon8:oFont) //Nome + CNPJ
	oDanfe:Say  (nRow3+225,050 ,AllTrim(aDadosEmp[3]) +" - "+ aDadosEmp[4] +" CEP: " + aDadosEmp[2]	,oFon8:oFont)

	oDanfe:Say  (nRow3+210,460,"Agência/Código Cedente"		,oFon8n:oFont)
	If (cAliasSE1)->A1_XBCOBOL == '104'
		oDanfe:Say  (nRow3+225, 505,ALLTRIM(aDadosBanco[3])+'/'+ALLTRIM(aDadosBanco[7])		,oFon8:oFont)

	ElseIf (cAliasSE1)->A1_XBCOBOL == '033'
		oDanfe:Say  (nRow3+225, 505,ALLTRIM(aDadosBanco[3])+'/'+cCodBen33					,oFon8:oFont)

	Else
		oDanfe:Say  (nRow3+225, 505,ALLTRIM(aDadosBanco[3]+"-"+cDVAge)+' / '+ALLTRIM(aDadosBanco[4])+IIF(xDac <> '','-' + xDac,'') ,oFon8:oFont)

	Endif

	oDanfe:Say  (nRow3+235,002 ,"Data de Emissão"       	,oFon8n:oFont)
	oDanfe:Say (nRow3+245,002, DTOC(aDadosTit[2])			,oFon8:oFont)


	oDanfe:Say  (nRow3+235,115 ,"Nro. Documento"        	,oFon8n:oFont)
	oDanfe:Say  (nRow3+245,145 ,aDadosTit[1]				,oFon8:oFont) 

	oDanfe:Say  (nRow3+235,250,"Espécie Doc."           	,oFon8n:oFont)
	oDanfe:Say  (nRow3+245,265,"DM"							,oFon8:oFont)

	oDanfe:Say  (nRow3+235,343,"Aceite"                 	,oFon8n:oFont)
	oDanfe:Say  (nRow3+245,353,"N"                      	,oFon8:oFont)

	oDanfe:Say  (nRow3+235,375,"Data Processamento"     	,oFon8n:oFont)
	oDanfe:Say  (nRow3+245,395,DTOC(aDadosTit[3])			,oFon8:oFont) 


	oDanfe:Say  (nRow3+235,460,"Carteira/Nosso Número"                                   		,oFon8n:oFont)
	IF ((cAliasSE1)->A1_XBCOBOL=='104')
		oDanfe:Say  (nRow3+245, 505,LEFT(_cNN,2)+'/'+SUBS(_cNN,3,LEN(_cNN)-3)+'-'+RIGHT(_cNN,1)	,oFon8:oFont)

	ElseIF((cAliasSE1)->A1_XBCOBOL=='399' .AND. nCobRegistrada == 1 )
		oDanfe:Say  (nRow3+245, 505,SUBS(_cNN,1,LEN(_cNN)-1)+'-'+RIGHT(_cNN,1)					,oFon8:oFont)

	ElseIF((cAliasSE1)->A1_XBCOBOL=='399' .AND. nCobRegistrada <> 1 )
		oDanfe:Say  (nRow3+245, 505,SUBS(_cNN,1,LEN(_cNN)-3)+'-'+RIGHT(_cNN,3)					,oFon8:oFont)

	ElseIf (cAliasSE1)->A1_XBCOBOL == "237"
		oDanfe:Say  (nRow3+245, 505,xCarteira +"/"+ SubStr(_cNN,1,11) +"-"+ Right(_cNN,1)		,oFon8:oFont)    

	ElseIf (cAliasSE1)->A1_XBCOBOL == "033"
		oDanfe:Say  (nRow3+245, 505,_cE1Numbco													,oFon8:oFont) 	            

	Else
		oDanfe:Say  (nRow3+245, 505,"3097391"+_cNN												,oFon8:oFont)

	EndIf

	oDanfe:Say  (nRow3+255,002 ,"Uso do Banco"          ,oFon8n:oFont)
	//oDanfe:Say  (nRow3+265,002 ,"8650"		                                  	,oFon8:oFont)

	oDanfe:Say  (nRow3+255,065 ,"CIP"		            ,oFon8n:oFont)
	oDanfe:Say  (nRow3+265,070 ,"000"		            ,oFon8:oFont)

	oDanfe:Say  (nRow3+255,115 ,"Carteira"              ,oFon8n:oFont)
	oDanfe:Say  (nRow3+265,135 ,xCarteira               ,oFon8:oFont)

	oDanfe:Say  (nRow3+255,180 ,"Moeda"                 ,oFon8n:oFont)
	oDanfe:Say  (nRow3+265,200 ,"R$"                    ,oFon8:oFont)

	oDanfe:Say  (nRow3+255,250,"Quantidade"             ,oFon8n:oFont)
	oDanfe:Say  (nRow3+255,375,"Valor"                  ,oFon8n:oFont)

	oDanfe:Say  (nRow3+255,460,"Valor do Documento"                          			,oFon8n:oFont)
	oDanfe:Say  (nRow3+265,545, AllTrim(Transform(aDadosTit[5],"@E 999,999,999.99")) 	, oFon8:oFont)

	oDanfe:Say  (nRow3+275,002 ,"Instruções (Todas informações deste bloqueto são de exclusiva responsabilidade do cedente)",oFon8n:oFont)

//oDanfe:Say  (nRow3+305,002 ,aBolText[3]                                        ,oFon8:oFont)
	oDanfe:Say  (nRow3+295,002 ,aBolText[1] ,oFon8:oFont)
	oDanfe:Say  (nRow3+305,002 ,aBolText[2] ,oFon8:oFont)
	oDanfe:Say  (nRow3+315,002 ,aBolText[3] ,oFon8:oFont)
	oDanfe:Say  (nRow3+325,002 ,aBolText[4] ,oFon8:oFont)

	oDanfe:Say  (nRow3+275,460,"(-)Desconto/Abatimento"                         ,oFon8n:oFont)
	oDanfe:Say  (nRow3+295,460,"(-)Outras Deduções"                             ,oFon8n:oFont)
	oDanfe:Say  (nRow3+315,460,"(+)Mora/Multa"                                  ,oFon8n:oFont)
	oDanfe:Say  (nRow3+335,460,"(+)Outros Acréscimos"                           ,oFon8n:oFont)
	oDanfe:Say  (nRow3+355,460,"(=)Valor Cobrado"                               ,oFon8n:oFont)

	oDanfe:Say  (nRow3+375,002 ,"Sacado"                                         ,oFon8n:oFont)
	oDanfe:Say  (nRow3+380,100 ,aDatSacado[1]+" ("+aDatSacado[2]+")"             ,oFon8:oFont)

	oDanfe:Say  (nRow3+390,100 ,aDatSacado[3]                                    ,oFon8:oFont)   //Endereço
	
	if Len(AllTrim(aDatSacado[7])) == 14
		oDanfe:Say  (nRow3+390,390,"CNPJ: "+TRANSFORM(aDatSacado[7],"@R 99.999.999/9999-99"),oFon8:oFont) // CGC
	Else
		oDanfe:Say  (nRow3+390,390,"CPF: "+TRANSFORM(aDatSacado[7],"@R 999.999.999-99"),oFon8:oFont) 	// CPF
	EndIf

	oDanfe:Say  (nRow3+405,100 ,aDatSacado[6]+"    "+aDatSacado[4]+" - "+aDatSacado[5],oFon8:oFont) // CEP+Cidade+Estado
	oDanfe:Say  (nRow3+405,400,Substr(aDadosTit[6],1,3)+Substr(aDadosTit[6],4)  ,oFon8:oFont)

	oDanfe:Say  (nRow3+407,002 ,"Sacador/Avalista"                               ,oFon8n:oFont)
	oDanfe:Say  (nRow3+421,370,"Autenticação Mecânica - Ficha de Compensação"                        ,oFon8n:oFont)

	oDanfe:Line (nRow3+2000,1800,nRow3+2690,1800 )
	oDanfe:Line (nRow3+2410,1800,nRow3+2410,2300 )
	oDanfe:Line (nRow3+2480,1800,nRow3+2480,2300 )
	oDanfe:Line (nRow3+2550,1800,nRow3+2550,2300 )
	oDanfe:Line (nRow3+2620,1800,nRow3+2620,2300 )
	oDanfe:Line (nRow3+2690,100 ,nRow3+2690,2300 )

	oDanfe:Line (nRow3+2850,100,nRow3+2850,2300  )    

	FWMsPrinter():FWMsBar("INT25",66.5,2.0,CB_RN_NN[1],oDanfe,.F.,Nil,Nil,0.017,0.82,Nil,Nil,"A",.F.)

	oDanfe:EndPage() // Finaliza a página

Return Nil

/*
+---------------------------------------------------------------------------+
!	Modulos 10 e 11			                                                !
+---------------------------------------------------------------------------+
*/
Static Function Modulo10(cData)
	LOCAL L,D,P := 0
	LOCAL B     := .F.
	L := Len(cData)
	B := .T.
	D := 0
	WHILE L > 0
		P := VAL(SUBSTR(cData, L, 1))
		IF (B)
			P := P * 2
			IF P > 9
				P := P - 9
			ENDIF
		ENDIF
		D := D + P
		L := L - 1
		B := !B
	ENDDO
	D := 10 - (Mod(D,10))
	IF D = 10
		D := 0
	ENDIF
RETURN(D)
/**/
Static Function Modulo11(cData)
	LOCAL L, D, P := 0
	L := LEN(cdata)
	D := 0
	P := 1
	WHILE L > 0
		P := P + 1
		D := D + (VAL(SUBSTR(cData, L, 1)) * P)
		IF P = 9
			P := 1
		ENDIF
		L := L - 1
	ENDDO
	D := 11 - (mod(D,11))
	IF (D == 0 .Or. D == 1 .Or. D > 9)
		D := 1
	ENDIF
RETURN(D)
/**/

Static Function Mod11NN(cData)

	LOCAL L, D, P := 0
	L := LEN(cdata)
	D := 0
	P := 1

	WHILE L > 0
		P := P + 1
		D := D + (VAL(SUBSTR(cData, L, 1)) * P)

		IF (nCobRegistrada == 1 .AND. (cAliasSE1)->A1_XBCOBOL == '399') //Apenas para HSBC - Cob. Registrada
			IF(P = 7)
				P := 1
			ENDIF
		ELSE  //Demais bancos
			IF (P = 9)
				P := 1
			ENDIF
		ENDIF
		L := L - 1
	ENDDO
	D := 11 - (mod(D,11))
	IF (nCobRegistrada == 1 .AND. (cAliasSE1)->A1_XBCOBOL == '399') //Apenas para HSBC - Cob. Registrada
		IF(D == 0 .OR. D == 1 .OR. D > 9)
			D := 0
		ENDIF
	ELSE
		IF (D > 9)
			D := 0
		ENDIF
	ENDIF

Return D


Static Function Modulo11NN(cData)

	Local nL, nD, nP := 0
	nL := Len(cData)
	nD := 0
	nP := 1

	While nL > 0
		nP := nP + 1
		nD := nD + (Val(SubStr(cData, nL, 1)) * nP)

		If nP == 7
			nP := 1
		EndIf

		nL := nL - 1
	End

	nD := 11 - (Mod(nD,11))

	If nD == 10
		cDv := "P"
	ElseIf nD > 10
		cDv := "0"
	Else
		cDv := Str(nD)
	EndIf

Return cDv


/*
+---------------------------------------------------------------------------+
!	Retorna os strings para impressão do Boleto                             !
+---------------------------------------------------------------------------+
*/
//--------------------->	ITAU	<---------------------------------------//
//CB = String para o cód.barras, RN = String com o número digitável
//Cobrança não identificada, número do boleto = Título + Parcela
//                             1     2      3       4         5       6      7         8      9
Static Function Ret_cBarra(cBanco,cAgencia,cConta,cCarteira,cNroDoc,nValor,cCodBanco,dVencto,cPref)

//LOCAL bldocnufinal := STRZERO(VAL(cNroDoc),8)
	LOCAL blvalorfinal := STRZERO(nValor*100,10)
	LOCAL dvnn         := 0
	LOCAL dvcb         := 0
	LOCAL dv           := 0
//LOCAL dvcc 		   := 0
	LOCAL dvcl         := 0
	LOCAL NN           := ''
	LOCAL RN           := ''
	LOCAL CB           := ''
	LOCAL CC	       := ''
	LOCAL CL	       := ''
//LOCAL DJ	       := ''
	LOCAL s            := ''
	LOCAL _nFator      := dVencto - If(dVencto >= Ctod('22/02/25'),CtoD('29/05/22'),CtoD("07/10/97"))
	LOCAL _nFator2     := dVencto - CTOD("03/07/2000")
	LOCAL _cCart	   := ''
	LOCAL _cConta	   := ''

//Local cCodBar   := ""
//Local cLinDig   := ""
//Local cNossoNum := ""
//Local cDigVer   := ""
//Local cAux      := ""   
//LOCAL NNB       := ""

//------------------> Dados Conta <-------------------------------------
	If (cAliasSE1)->A1_XBCOBOL == '341'
		_cCart	   := '109'
		_cConta	   := PADL(ALLTRIM(STRTRAN(cConta,"-","")),6,"0")
	ElseIf (cAliasSE1)->A1_XBCOBOL == "237"
		_cCart := "09"
	ElseIf (cAliasSE1)->A1_XBCOBOL == '399'
		_cCart	   := '00'
		_cConta	   := PADL(ALLTRIM(STRTRAN(cConta,"-","")),7,"0")
	ElseIf (cAliasSE1)->A1_XBCOBOL == '001'
		_cCart	   := '17'
	ElseIf (cAliasSE1)->A1_XBCOBOL == '033'
		_cCart	   := '101'
		_cConta	   := PADL(ALLTRIM(STRTRAN(cConta,"-","")),9,"0")
	Else
		_cConta	   := PADL(ALLTRIM(STRTRAN(cConta,"-","")),10,"0")
	EndIf

//------------------> NOSSO NUMERO <-------------------------------------
	cNTit := (cAliasSE1)->E1_PREFIXO+(cAliasSE1)->E1_NUM+(cAliasSE1)->E1_PARCELA+(cAliasSE1)->E1_TIPO

	SEE->(DBSelectArea('SEE'))
	SEE->(DBSEEK(xFilial('SEE')+(cAliasSE1)->A1_XBCOBOL+(cAliasSE1)->E1_AGEDEP +(cAliasSE1)->E1_CONTA+cSubConta))
	SE1->(DBGoTop())

	If SE1->(MSSeek(xFilial("SE1")+cNTit))

		If ((cAliasSE1)->A1_XBCOBOL == '399')//HSBC - Cob. Registrada (Tam.10)
			NN := SE1->E1_NUMBCO //NNHsbc()
		ElseIf ((cAliasSE1)->A1_XBCOBOL == '341')
			NN := SE1->E1_NUMBCO //NNItau()
		ElseIf ((cAliasSE1)->A1_XBCOBOL == '104')
			NN := SE1->E1_NUMBCO //NNCef()
			CC := PADL(ALLTRIM(STRTRAN(SEE->EE_CODEMP,"-","")),7,"0")
		ElseIf ((cAliasSE1)->A1_XBCOBOL == "237")
			NN := SE1->E1_NUMBCO //NN237()
		ElseIf ((cAliasSE1)->A1_XBCOBOL == "001")
			NN := SE1->E1_NUMBCO //NN001()
		ElseIf ((cAliasSE1)->A1_XBCOBOL == "033")
			NN := SE1->E1_NUMBCO //NN033()
		EndIf

	EndIf


	If ((cAliasSE1)->A1_XBCOBOL == "033")

		//Constroi a linha digitável
		banco := "033"

		//1o Bloco
		_cDigNNum	:=	u_digMod11(Substr(SE1->E1_NUMBCO,1,12)) // Digito verificador do nosso numero para cobrança santander
		_cE1Numbco	:=	alltrim(substr(SE1->E1_NUMBCO,1,12))+ _cDigNNum

		cLinha1:=banco + '99' + Substr(SEE->EE_CODEMP,1,4)
		cLinha1+=DigitoBol(cLinha1)
		cLinha1:=SubStr(cLinha1,1,5)+"."+SubStr(cLinha1,6,len(cLinha1)) + "  "

		//2o Bloco
		cLinha2:=substr(Substr(SEE->EE_CODEMP,5,len(SEE->EE_CODEMP)),1,3) +	substr(_cE1Numbco,1,7)
		cLinha2+=DigitoBol(cLinha2)
		cLinha2:=SubStr(cLinha2,1,5)+"."+SubStr(cLinha2,6,len(cLinha2)) + "  "

		//3o Bloco
		cLinha3:=alltrim(SubStr(_cE1Numbco,8,len(_cE1Numbco))) + "0" + _cCart
		cLinha3+=DigitoBol(cLinha3)
		cLinha3:=alltrim(SubStr(cLinha3,1,5))+"."+alltrim(SubStr(cLinha3,6,len(cLinha3))) + "  "

		//Montagem do valor liquido para o boleto (Vinicius SMS em 02/06/2014)
		nVlrAbat := SomaAbat(SE1->E1_PREFIXO,SE1->E1_NUM,SE1->E1_PARCELA,"R",SE1->E1_MOEDA,dDataBase,SE1->E1_CLIENTE,SE1->E1_LOJA)
		nVlrDoc	 := Round((((SE1->E1_SALDO+SE1->E1_ACRESC)-SE1->E1_DECRESC)*100)-(nVlrAbat*100),0)/100

		//4o Bloco (digitao)
		cDigitao := DigBar(banco+'9'+ Str(_nFator,4) + StrZero((nVlrDoc)*100,10) + "9" + Substr(SEE->EE_CODEMP,1,7) + _cE1Numbco + "0" + _cCart)

		//5o Bloco
		cLinha4:=alltrim(Str(_nFator,4)) + StrZero((nVlrDoc)*100,10)

		RN := cLinha1 + cLinha2 + cLinha3 + cDigitao + "  " + cLinha4

		//Prepara Cod. de Barras
		CB := banco+'9'+ cDigitao + Str(_nFator,4) + StrZero((nVlrDoc)*100,10) + "9" + Substr(SEE->EE_CODEMP,1,7) + _cE1Numbco + "0" + _cCart

	End

/*---------------------------------------------------------------------------------------------
|                                                                                             |
------------------------>		HSBC	<------------------------------------------------------*/
If ((cAliasSE1)->A1_XBCOBOL == '399')
	//Calcula DV do Nosso Numero
	//dvnn := Mod11NN(NN)
	//NN   := SubStr(NN,1,10) + Alltrim(Str(dvnn))
	NN   := SubStr(NN,1,11)
	//Definicao do CODIGO DE BARRAS
	s := cBanco + Alltrim(Str(_nFator2)) + blvalorfinal + SubStr(NN,1,11) + SubStr(AllTrim(cAgencia),1,4) + SubStr(_cConta,1,7) + '001'
	dvcb := modulo11(s)
	CB := SubStr(s, 1, 4) + AllTrim(Str(dvcb)) + SubStr(s, 5, 39)
	
	//LINHA DIGITAVEL (Representacao Numerica Cod. Barra)
	//	CAMPO 1:
	//	AAA = Codigo do banco na Camara de Compensacao
	//	  B = Codigo da moeda, sempre 9
	//DDDDD = Cinco primeiros digitos no nosso numero
	//	  X = DAC que amarra o campo, calculado pelo Modulo 10 da String do campo
	s    := cBanco + SUBSTR(NN,1,5)
	dv   := modulo10(s)
	RN   := SUBSTR(s, 1, 5) + '.' + SUBSTR(s, 6, 4) + AllTrim(Str(dv)) + '  '
	//	CAMPO 2:
	//	DDDDDD = Restante do Nosso Numero
	//    AAAA = Cod. Agencia
	//	     Y = DAC que amarra o campo, calculado pelo Modulo 10 da String do campo
	s    := SUBSTR(NN,6,6) + SUBSTR(cAgencia,1,4)
	dv   := modulo10(s)
	RN   := RN + SUBSTR(s, 1, 5) + '.' + SUBSTR(s, 6, 5) + AllTrim(Str(dv)) + '  '
	//	CAMPO 3:
	// GGGGGGG = Numero da Conta + DAC da mesma
	//	   HH  = Zeros (Nao utilizado)
	//       C = Cod. Aplicativo = 1
	//	     Z = DAC que amarra o campo, calculado pelo Modulo 10 da String do campo
	s    := _cConta + '001'
	dv   := modulo10(s)
	RN   := RN + SUBSTR(s, 1, 5) + '.' + SUBSTR(s, 6, 5) + AllTrim(Str(dv)) + '  '
	//	CAMPO 4:
	//	     K = DAC do Codigo de Barras
	RN   := RN + AllTrim(Str(dvcb)) + '  '
	//*	CAMPO 5:
	//	      UUUU = Fator de Vencimento
	//	VVVVVVVVVV = Valor do Titulo
	RN   := RN + Alltrim(Str(_nFator2)) + blvalorfinal
	
	/*---------------------------------------------------------------------------------------------
	|                                                                                             |
	---------------------------------> ITAU <----------------------------------------------------*/
ElseIf ((cAliasSE1)->A1_XBCOBOL == '341')
	//Calcula DV do Nosso Numero
	s:= AllTrim(cAgencia) + SubStr(alltrim(_cConta),1,5) + _cCart + SubStr(alltrim(NN),1,8)
	dvnn := modulo10(s)
	//Definicao do CODIGO DE BARRAS
	s := cBanco + Alltrim(Str(_nFator)) + blvalorfinal + _cCart + SubStr(alltrim(NN),1,8)+Alltrim(Str(dvnn)) +AllTrim(cAgencia) + _cConta + '000'
	dvcb := modulo11(s)
	CB := SubStr(s, 1, 4) + AllTrim(Str(dvcb)) + SubStr(s, 5, 39)
	
	//LINHA DIGITAVEL (Representacao Numerica Cod. Barra)
	//	CAMPO 1:
	//	AAA = Codigo do banco na Camara de Compensacao
	//	  B = Codigo da moeda, sempre 9
	//	CCC = Codigo da Carteira de Cobranca
	//	 DD = Dois primeiros digitos no nosso numero
	//	  X = DAC que amarra o campo, calculado pelo Modulo 10 da String do campo
	s    := cBanco + _cCart + SUBSTR(NN,1,2)
	dv   := modulo10(s)
	RN   := SUBSTR(s, 1, 5) + '.' + SUBSTR(s, 6, 4) + AllTrim(Str(dv)) + '  '
	//	CAMPO 2:
	//	DDDDDD = Restante do Nosso Numero
	//	     E = DAC do campo Agencia/Conta/Carteira/Nosso Numero
	//	   FFF = Tres primeiros numeros que identificam a agencia
	//	     Y = DAC que amarra o campo, calculado pelo Modulo 10 da String do campo
	s    := SUBSTR(NN,3,6) + Alltrim(Str(dvnn)) + SUBSTR(cAgencia, 1, 3)
	dv   := modulo10(s)
	RN   := RN + SUBSTR(s, 1, 5) + '.' + SUBSTR(s, 6, 5) + AllTrim(Str(dv)) + '  '
	//	CAMPO 3:
	//	     F = Restante do numero que identifica a agencia
	//	GGGGGG = Numero da Conta + DAC da mesma
	//	   HHH = Zeros (Nao utilizado)
	//	     Z = DAC que amarra o campo, calculado pelo Modulo 10 da String do campo
	s    := SUBSTR(cAgencia, 4, 1) + _cConta + '000'
	dv   := modulo10(s)
	RN   := RN + SUBSTR(s, 1, 5) + '.' + SUBSTR(s, 6, 5) + AllTrim(Str(dv)) + '  '
	//	CAMPO 4:
	//	     K = DAC do Codigo de Barras
	RN   := RN + AllTrim(Str(dvcb)) + '  '
	//*	CAMPO 5:
	//	      UUUU = Fator de Vencimento
	//	VVVVVVVVVV = Valor do Titulo
	RN   := RN + Alltrim(Str(_nFator)) + blvalorfinal

// Banco Bradesco # Implementado em 11/08/2017 dirlei@afsouza
ElseIf ((cAliasSE1)->A1_XBCOBOL == "237")

	// Nosso Número: poderá ser gerado a partir de 00000000001, 00000000002, 11 posições,
	// devendo ser atribuído numero diferenciado para identificação de cada documento na
	// Cobrança Bradesco.
	// Para o cálculo do dígito, será necessário acrescentar o número da carteira à esquerda
	// antes do Nosso Número, e aplicar o módulo 11, com base 7.
	//cAux := NN
	//NN   := _cCart + NN
	//dvNN := Mod11NN(NN) 
	//NN   := cAux + AllTRim(Str(dvNN))

	// Grava E1_NUMBCO
	//RecLock("SE1",.F.)
	//SE1->E1_NUMBCO := NN
	//MsUnlock("SE1")

	/*CAMPO LIVRE*:
	20 a 23  4 Agência Beneficiária (Sem o digito verificador, completar com zeros a esquerda quando necessário)
	24 a 25  2 Carteira
	26 a 36 11 Número do Nosso Número (Sem o digito verificador)
	37 a 43  7 Conta do Beneficiário (Sem o digito verificador, completar com zeros a esquerda quando necessário)
	44 a 44	 1 Zero
	*/
	CL := StrZero(Val(cAgencia),4) + cCarteira + Left(NN,11) + SubStr(cConta,1,7) + "0"

	/*Definicao do CODIGO DE BARRAS
	01 a 03  3 Identificação do Banco
	04 a 04  1 Código da Moeda (Real = 9, Outras=0)
	05 a 05  3 Dígito verificador do Código de Barras
	06 a 09  4 Fator de Vencimento
	10 a 19 10 Valor
	*/	
	s    := cBanco + AllTrim(Str(_nFator)) + blvalorfinal + CL
	dvCB := Modulo11(s)
	CB   := SubStr(s, 1, 4) + AllTrim(Str(dvCB)) + SubStr(s, 5)

	//LINHA DIGITAVEL (Representacao Numerica Cod. Barra)
	//	CAMPO 1:
	//	AAA = Codigo do banco na Camara de Compensacao
	//	  B = Codigo da moeda, sempre 9
	//XXXXX = 1ª parte do Campo Livre = 5 primeiras posições
	//	  X = DAC que amarra o campo, calculado pelo Modulo 10 da String do campo
	s  := cBanco + SubStr(CL,1,5)
	dv := Modulo10(s)
	RN := SubStr(s, 1, 5) +"."+ SubStr(s, 6, 4) + AllTrim(Str(dv)) +"  "

	//	CAMPO 2:
	//XXXXXXXXXX = 2ª parte do Campo Livre = da 6a. a 15a. posição
	//	       Y = DAC que amarra o campo, calculado pelo Modulo 10 da String do campo
	s  := SubStr(CL,6,10)
	dv := Modulo10(s)
	RN := RN + SubStr(s, 1, 5) +"."+ SubStr(s, 6, 5) + AllTrim(Str(dv)) +"  "

	//	CAMPO 3:
	//XXXXXXXXXX = 3ª parte do Campo Livre = 16a. a 25a. posição
	//        D2 = Dígito Verificador do Campo Livre
	//	       Z = DAC que amarra o campo, calculado pelo Modulo 10 da String do campo
	s  := SubStr(CL,16,10)
	dv := Modulo10(s)
	RN := RN + SubStr(s, 1, 5) +"."+ SubStr(s, 6, 5) + AllTrim(Str(dv)) +"  "

	//	CAMPO 4:
	//	     K = DAC do Codigo de Barras
	RN := RN + AllTrim(Str(dvcb)) +"  "

	//*	CAMPO 5:
	//	      UUUU = Fator de Vencimento
	//	VVVVVVVVVV = Valor do Titulo
	RN := RN + AllTrim(Str(_nFator)) + blvalorfinal

ElseIf ((cAliasSE1)->A1_XBCOBOL == "001")

	// Nosso Número: poderá ser gerado a partir de 00000000001, 00000000002, 11 posições,
	// devendo ser atribuído numero diferenciado para identificação de cada documento na
	// Cobrança Bradesco.
	// Para o cálculo do dígito, será necessário acrescentar o número da carteira à esquerda
	// antes do Nosso Número, e aplicar o módulo 11, com base 7.
	//cAux := NN
	//NN   := _cCart + NN
	//dvNN := Mod11NN(NN)
	//NN   := cAux + AllTRim(Str(dvNN))

	// Grava E1_NUMBCO
	//RecLock("SE1",.F.)
	//SE1->E1_NUMBCO := NN
	//MsUnlock("SE1")

	/*CAMPO LIVRE*:
	20 a 23  4 Agência Beneficiária (Sem o digito verificador, completar com zeros a esquerda quando necessário)
	24 a 25  2 Carteira
	26 a 36 11 Número do Nosso Número (Sem o digito verificador)
	37 a 43  7 Conta do Beneficiário (Sem o digito verificador, completar com zeros a esquerda quando necessário)
	44 a 44	 1 Zero
	*/
	//	CL := StrZero(Val(cAgencia),4) + cCarteira + Left(NN,11) + SubStr(cConta,1,7) + "0"
	CL := "0000003097391" + AllTrim(NN)+ "17"

	/*Definicao do CODIGO DE BARRAS
	01 a 03  3 Identificação do Banco
	04 a 04  1 Código da Moeda (Real = 9, Outras=0)
	05 a 05  3 Dígito verificador do Código de Barras
	06 a 09  4 Fator de Vencimento
	10 a 19 10 Valor
	*/	
	s    := cBanco + AllTrim(Str(_nFator)) + blvalorfinal + CL
	dvCB := Modulo11(s)
	CB   := SubStr(s, 1, 4) + AllTrim(Str(dvCB)) + SubStr(s, 5)

	//LINHA DIGITAVEL (Representacao Numerica Cod. Barra)
	//	CAMPO 1:
	//	AAA = Codigo do banco na Camara de Compensacao
	//	  B = Codigo da moeda, sempre 9
	//XXXXX = 1ª parte do Campo Livre = 5 primeiras posições
	//	  X = DAC que amarra o campo, calculado pelo Modulo 10 da String do campo
	s  := cBanco + SubStr(CL,1,5)
	dv := Modulo10(s)
	RN := SubStr(s, 1, 5) +"."+ SubStr(s, 6, 4) + AllTrim(Str(dv)) +"  "

	//	CAMPO 2:
	//XXXXXXXXXX = 2ª parte do Campo Livre = da 6a. a 15a. posição
	//	       Y = DAC que amarra o campo, calculado pelo Modulo 10 da String do campo
	s  := SubStr(CL,6,10)
	dv := Modulo10(s)
	RN := RN + SubStr(s, 1, 5) +"."+ SubStr(s, 6, 5) + AllTrim(Str(dv)) +"  "

	//	CAMPO 3:
	//XXXXXXXXXX = 3ª parte do Campo Livre = 16a. a 25a. posição
	//        D2 = Dígito Verificador do Campo Livre
	//	       Z = DAC que amarra o campo, calculado pelo Modulo 10 da String do campo
	s  := SubStr(CL,16,10)
	dv := Modulo10(s)
	RN := RN + SubStr(s, 1, 5) +"."+ SubStr(s, 6, 5) + AllTrim(Str(dv)) +"  "

	//	CAMPO 4:
	//	     K = DAC do Codigo de Barras
	RN := RN + AllTrim(Str(dvcb)) +"  "

	//*	CAMPO 5:
	//	      UUUU = Fator de Vencimento
	//	VVVVVVVVVV = Valor do Titulo
	RN := RN + AllTrim(Str(_nFator)) + blvalorfinal


	/*Definicao do CODIGO DE BARRAS
	01 a 03  3 Identificação do Banco
	04 a 04  1 Código da Moeda (Real = 9, Outras=0)
	05 a 05  3 Dígito verificador do Código de Barras
	06 a 09  4 Fator de Vencimento
	10 a 19 10 Valor
	
	/*		Código de barras:
	//CB = String para o cód.barras, RN = String com o número digitável
	
00199755200000558643007170000000000313146880
				   3007170000000
0019dVVVV$$$$$$$$$$000000CCCCCCCnnnnnnnnnncc

	convenio:3097391
	Linha digitável

	00193.00714  70000.000003  03131.468807  9  75520000055864
	00190.0000d  0CCCC.CCCnnd  nnnnn.nnnccd  D  VVVV$$$$$$$$$$

	Onde:

	C: Número do convênio     n: Nosso número (numeração livre)
	D: Dv geral               d: dígito verificador
	c: Carteira               a: Agência
	$: valor                  V: fator de vencimento
	&: Conta corrente
	*/


	/*---------------------------------------------------------------------------------------------
	|                                                                                             |
	------------------------>		CEF 	<------------------------------------------------------*/
ElseIf ((cAliasSE1)->A1_XBCOBOL == '104')
	/*NOSSO NÚMERO*:
	- O Nosso Número no SIGCB é composto de 17 posições, sendo as 02 posições iniciais para identificar a
	Carteira e as 15 posições restantes são para livre utilização pelo Cedente.
	- Formato: XY NNNNNNNNNNNNNNN -D, onde:
	X Modalidade/Carteira de Cobrança (1-Registrada/2-Sem Registro)
	Y Emissão do bloqueto (4-Cedente)
	NNNNNNNNNNNNNNN Nosso Número (15 posições livres do Cedente)
	D *Dígito Verificador
	* Dígito Verificador do Nosso Número calculado através do Modulo 11*/
	NN   := '14'+SubStr(NN,1,15)
	dvnn := Mod11NN(NN)//Permite zero(0)
	NN   := SubStr(NN,1,17) + Alltrim(Str(dvnn))
	/*CAMPO LIVRE*:
	Código do Cedente e DV do Código do Cedente
	Nosso Número – Seqüência 1 							= 3ª a 5ª posição do Nosso Número
	Tipo de Cobrança (1-Registrada / 2-Sem Registro)	= 1ª posição do Nosso Numero:
	Nosso Número – Seqüência 2 							= 6ª a 8ª posição do Nosso Número
	Identificador da Emissão do Bloqueto (4-Cedente)	= 2ª posição do Nosso Número:
	Nosso Número – Seqüência 3 							= 9ª a 17ª posição do Nosso Número
	DV do Campo Livre
	*/
	CL	 := SUBSTR(CC,1,7) + SUBSTR(NN,3,3) + '1' +SUBSTR(NN,6,3) + '4' + SUBSTR(NN,9,9)
	dvcl := Mod11NN(CL)//Permite zero(0)

	//Definicao do CODIGO DE BARRAS
	s := cBanco + Alltrim(Str(_nFator)) + blvalorfinal + SUBSTR(CL,1,24) + AllTrim(Str(dvcl))
	dvcb := modulo11(s)
	CB := SubStr(s, 1, 4) + AllTrim(Str(dvcb)) + SubStr(s, 5, 39)


	//LINHA DIGITAVEL (Representacao Numerica Cod. Barra)
	//	CAMPO 1:
	//	AAA = Codigo do banco na Camara de Compensacao
	//	  B = Codigo da moeda, sempre 9
	//XXXXX = 1ª parte do Campo Livre
	//	  X = DAC que amarra o campo, calculado pelo Modulo 10 da String do campo
	//Solicitar CC (Codigo Cedente)
	s    := cBanco + SUBSTR(CL,1,5)
	dv   := modulo10(s)
	RN   := SUBSTR(s, 1, 5) + '.' + SUBSTR(s, 6, 4) + AllTrim(Str(dv)) + '  '
	//	CAMPO 2:
	//XXXXXXXXXX = 2ª parte do Campo Livre
	//	       Y = DAC que amarra o campo, calculado pelo Modulo 10 da String do campo
	s    := SUBSTR(CL,6,10)
	dv   := modulo10(s)
	RN   := RN + SUBSTR(s, 1, 5) + '.' + SUBSTR(s, 6, 5) + AllTrim(Str(dv)) + '  '
	//	CAMPO 3:
	//XXXXXXXXXX = 3ª parte do Campo Livre
	//        D2 = Dígito Verificador do Campo Livre
	//	       Z = DAC que amarra o campo, calculado pelo Modulo 10 da String do campo
	s    := SUBSTR(CL,16,9) + AllTrim(Str(dvcl))
	dv   := modulo10(s)
	RN   := RN + SUBSTR(s, 1, 5) + '.' + SUBSTR(s, 6, 5) + AllTrim(Str(dv)) + '  '
	//	CAMPO 4:
	//	     K = DAC do Codigo de Barras
	RN   := RN + AllTrim(Str(dvcb)) + '  '
	//*	CAMPO 5:
	//	      UUUU = Fator de Vencimento
	//	VVVVVVVVVV = Valor do Titulo
	RN   := RN + Alltrim(Str(_nFator)) + blvalorfinal

EndIf

RETURN({CB,RN,NN})

/*/{Protheus.doc} DIGBAR
Cálculo do Díg Verificador do Cod.Barras - Bco Santander MOD(11) Pesos (2 a 9)  
@type function
@version 1.0 
@author Alfred Andersen
@since 10/01/2023
/*/
Static Function DIGBAR(xPar01)

	Local nCont	:=0
	Local cPeso	:=2
	Local i

	StrTran(xPar01," ","")

	For i:=Len(xPar01) To 1 Step -1
		nCont:=nCont+(Val(SUBSTR(xPar01,i,1))*cPeso)
		cPeso:=cPeso+1
		if cPeso>9
			cPeso:=2
		endif
	Next i

	resto:=((ncont*10)%11)

	If resto==0 .or. resto==1 .or. resto > 9
		nDigbar:='1'
	Else
		nDigbar:=Str(resto,1)
	Endif

Return (nDigbar)

/*/{Protheus.doc} DigitoBol
Cálculo dos dígitos da Linha Digitável - Banco Santander
@type function
@version 1.0 
@author Alfred Andersen
@since 10/01/2023
/*/
Static Function DigitoBol(xPar01)

	Local nCont		:=0
	Local nValor	:=0
	Local cPeso		:=2
	Local i

	StrTran(xPar01," ","")

	For i:=Len(xPar01) to 1 Step -1
		nValor:=(Val(SUBSTR(xPar01,i,1))*cPeso)

		If nValor>9
			nValor:=val(substr(alltrim(str(nValor)),1,1))+val(substr(alltrim(str(nValor)),2,1))
		Endif

		nCont:=nCont+nValor

		cPeso--

		If cPeso==0
			cPeso:=2
		Endif

	Next i

	resto:=(nCont%10)
	If	resto <> 0
		resto:= 10-resto
	Endif

Return( alltrim(Str(resto)) )

